// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: runner.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ChartRef struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Namespace     string                 `protobuf:"bytes,2,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Maintainer    string                 `protobuf:"bytes,3,opt,name=maintainer,proto3" json:"maintainer,omitempty"`
	SchemaVersion string                 `protobuf:"bytes,4,opt,name=schemaVersion,proto3" json:"schemaVersion,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChartRef) Reset() {
	*x = ChartRef{}
	mi := &file_runner_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChartRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChartRef) ProtoMessage() {}

func (x *ChartRef) ProtoReflect() protoreflect.Message {
	mi := &file_runner_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChartRef.ProtoReflect.Descriptor instead.
func (*ChartRef) Descriptor() ([]byte, []int) {
	return file_runner_proto_rawDescGZIP(), []int{0}
}

func (x *ChartRef) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ChartRef) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *ChartRef) GetMaintainer() string {
	if x != nil {
		return x.Maintainer
	}
	return ""
}

func (x *ChartRef) GetSchemaVersion() string {
	if x != nil {
		return x.SchemaVersion
	}
	return ""
}

type InstantiateReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ref           *ChartRef              `protobuf:"bytes,1,opt,name=ref,proto3" json:"ref,omitempty"`
	Pull          bool                   `protobuf:"varint,2,opt,name=pull,proto3" json:"pull,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InstantiateReq) Reset() {
	*x = InstantiateReq{}
	mi := &file_runner_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InstantiateReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InstantiateReq) ProtoMessage() {}

func (x *InstantiateReq) ProtoReflect() protoreflect.Message {
	mi := &file_runner_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InstantiateReq.ProtoReflect.Descriptor instead.
func (*InstantiateReq) Descriptor() ([]byte, []int) {
	return file_runner_proto_rawDescGZIP(), []int{1}
}

func (x *InstantiateReq) GetRef() *ChartRef {
	if x != nil {
		return x.Ref
	}
	return nil
}

func (x *InstantiateReq) GetPull() bool {
	if x != nil {
		return x.Pull
	}
	return false
}

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_runner_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_runner_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_runner_proto_rawDescGZIP(), []int{2}
}

var File_runner_proto protoreflect.FileDescriptor

const file_runner_proto_rawDesc = "" +
	"\n" +
	"\frunner.proto\x12\x05proto\"\x82\x01\n" +
	"\bChartRef\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1c\n" +
	"\tnamespace\x18\x02 \x01(\tR\tnamespace\x12\x1e\n" +
	"\n" +
	"maintainer\x18\x03 \x01(\tR\n" +
	"maintainer\x12$\n" +
	"\rschemaVersion\x18\x04 \x01(\tR\rschemaVersion\"G\n" +
	"\x0eInstantiateReq\x12!\n" +
	"\x03ref\x18\x01 \x01(\v2\x0f.proto.ChartRefR\x03ref\x12\x12\n" +
	"\x04pull\x18\x02 \x01(\bR\x04pull\"\a\n" +
	"\x05Empty2\x97\x01\n" +
	"\rRunnerService\x12'\n" +
	"\x04Pull\x12\x0f.proto.ChartRef\x1a\f.proto.Empty\"\x00\x124\n" +
	"\vInstantiate\x12\x15.proto.InstantiateReq\x1a\f.proto.Empty\"\x00\x12'\n" +
	"\x04Kill\x12\x0f.proto.ChartRef\x1a\f.proto.Empty\"\x00B\"Z github.com/c12s/gprunner/cmd/apib\x06proto3"

var (
	file_runner_proto_rawDescOnce sync.Once
	file_runner_proto_rawDescData []byte
)

func file_runner_proto_rawDescGZIP() []byte {
	file_runner_proto_rawDescOnce.Do(func() {
		file_runner_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_runner_proto_rawDesc), len(file_runner_proto_rawDesc)))
	})
	return file_runner_proto_rawDescData
}

var file_runner_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_runner_proto_goTypes = []any{
	(*ChartRef)(nil),       // 0: proto.ChartRef
	(*InstantiateReq)(nil), // 1: proto.InstantiateReq
	(*Empty)(nil),          // 2: proto.Empty
}
var file_runner_proto_depIdxs = []int32{
	0, // 0: proto.InstantiateReq.ref:type_name -> proto.ChartRef
	0, // 1: proto.RunnerService.Pull:input_type -> proto.ChartRef
	1, // 2: proto.RunnerService.Instantiate:input_type -> proto.InstantiateReq
	0, // 3: proto.RunnerService.Kill:input_type -> proto.ChartRef
	2, // 4: proto.RunnerService.Pull:output_type -> proto.Empty
	2, // 5: proto.RunnerService.Instantiate:output_type -> proto.Empty
	2, // 6: proto.RunnerService.Kill:output_type -> proto.Empty
	4, // [4:7] is the sub-list for method output_type
	1, // [1:4] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_runner_proto_init() }
func file_runner_proto_init() {
	if File_runner_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_runner_proto_rawDesc), len(file_runner_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_runner_proto_goTypes,
		DependencyIndexes: file_runner_proto_depIdxs,
		MessageInfos:      file_runner_proto_msgTypes,
	}.Build()
	File_runner_proto = out.File
	file_runner_proto_goTypes = nil
	file_runner_proto_depIdxs = nil
}
