services:
  buildkitd:
    image: moby/buildkit:v0.29.0
    privileged: true
    volumes:
      # socket dir
      - buildkit-sock:/run/buildkit
      # layer cache
      - buildkit-cache:/var/lib/buildkit
    healthcheck:
      test: ["CMD", "buildctl", "debug", "workers"]
      interval: 5s
      timeout: 5s
      retries: 12
      start_period: 15s

  runner:
    build:
      context: ..
      dockerfile: cmd/Dockerfile
    depends_on:
      buildkitd:
        condition: service_healthy
    environment:
      PGRUNNER_CACHE: ${PGRUNNER_CACHE}
      KRAFTKIT_BUILDKIT_HOST: ${KRAFTKIT_BUILDKIT_HOST}
      KRAFTKIT_NO_PROMPT: ${KRAFTKIT_NO_PROMPT}
      KRAFTKIT_LOG_TYPE: ${KRAFTKIT_LOG_TYPE}
      KRAFTKIT_NO_COLOR: ${KRAFTKIT_NO_COLOR}
      KRAFTKIT_NO_CHECK_UPDATES: ${KRAFTKIT_NO_CHECK_UPDATES}
    volumes:
      # image/build mount
      - ./data:/app/data
      # socket access with read only options
      - buildkit-sock:/run/buildkit:ro
      # kraft package store
      - kraft-store:/root/.local/share/kraftkit
    devices:
      - /dev/kvm

volumes:
  buildkit-sock:
  buildkit-cache:
  kraft-store: